- hosts: default
  sudo: true
  tasks:
  - name: Check if release 10.2-RELEASE exists
    iocage: state=fetched release=10.2-RELEASE

  - name: Check if basejail exists
    iocage: state=exists tag=test_basejail_10.2-RELEASE
    ignore_errors: true

  - name: Check if base jail can be created
    iocage: state=basejail tag=test_basejail_10.2-RELEASE release=10.2-RELEASE
# Basejails can't be made templates
  - name: Verify that base jail cannot be converted
    iocage: state=set tag=test_basejail_10.2-RELEASE properties="istemplate=yes"
    ignore_errors: true
  - name: Check if clone can be had
    iocage: state=cloned tag=test_jail clone_from=test_basejail_10.2-RELEASE
  - name: Verify that base jail cannot be converted
    iocage: state=set tag=test_jail properties="istemplate=yes"
    ignore_errors: true
  - name: Check if cloned test jail can be destroyed
    iocage: state=absent tag=test_jail
# check with an absent jail. should produce lots of ignored errors.
  - name: Check if absent jail can't be destroyed
    iocage: state=absent tag=absent
    ignore_errors: yes
  - name: Check if absent jail can't be stopped
    iocage: state=stopped tag=absent
    ignore_errors: yes
  - name: Check if absent jail can be restarted
    iocage: state=restarted tag=absent
    ignore_errors: yes
  - name: Check if absent jail can be started
    iocage: state=started tag=absent
    ignore_errors: yes

# check everything
  - name: Check if test jail can be cloned
    iocage: state=cloned clone_from=test_basejail_10.2-RELEASE tag=test_jail
  - name: Check if test jail can be started
    iocage: state=started tag=test_jail
  - name: Check if test jail that's started -- is started
    iocage: state=started tag=test_jail
  - name: Check if exec works in test jail
    iocage: state=exec tag=test_jail cmd="/bin/ls -la /root"
  - name: Check if test jail can be restarted
    iocage: state=restarted tag=test_jail
  - name: Check if test jail can be stopped
    iocage: state=stopped tag=test_jail
  - name: Check if test jail can be started again
    iocage: state=started tag=test_jail
  - name: Check if test jail can be destroyed
    iocage: state=absent tag=test_jail

  - name: Check if base jail can be destroyed
    iocage: state=absent tag=test_basejail_10.2-RELEASE
